export const BATTERY_LIST_REQUEST = "BATTERY_LIST_REQUEST";
export const BATTERY_LIST_SUCCESS = "BATTERY_LIST_SUCCESS";
export const BATTERY_LIST_FAIL = "BATTERY_LIST_FAIL";

export const BATTERY_DETAILS_REQUEST = "BATTERY_DETAILS_REQUEST";
export const BATTERY_DETAILS_SUCCESS = "BATTERY_DETAILS_SUCCESS";
export const BATTERY_DETAILS_FAIL = "BATTERY_DETAILS_FAIL";

export const BATTERY_CREATE_REQUEST = "BATTERY_CREATE_REQUEST";
export const BATTERY_CREATE_SUCCESS = "BATTERY_CREATE_SUCCESS";
export const BATTERY_CREATE_FAIL = "BATTERY_CREATE_FAIL";
export const BATTERY_CREATE_RESET = "BATTERY_CREATE_RESET";

export const BATTERY_UPDATE_REQUEST = "BATTERY_UPDATE_REQUEST";
export const BATTERY_UPDATE_SUCCESS = "BATTERY_UPDATE_SUCCESS";
export const BATTERY_UPDATE_FAIL = "BATTERY_UPDATE_FAIL";
export const BATTERY_UPDATE_RESET = "BATTERY_UPDATE_RESET";

export const BATTERY_DELETE_REQUEST = "BATTERY_DELETE_REQUEST";
export const BATTERY_DELETE_SUCCESS = "BATTERY_DELETE_SUCCESS";
export const BATTERY_DELETE_FAIL = "BATTERY_DELETE_FAIL";
export const BATTERY_DELETE_RESET = "BATTERY_DELETE_RESET";
